import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import CommonLayout from "@/components/CommonLayout/CommonLayout";
import Provider from "@/utils/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Live Chat",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/live-chat-icon.svg", // /public path
  },
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <Provider>
          <CommonLayout>{children}</CommonLayout>
        </Provider>
      </body>
    </html>
  );
}
